#!/bin/sh
mkdir -p ~/.config
ln -s ~/dotfiles/bspwm ~/.config/bspwm
ln -s ~/dotfiles/sxhkd ~/.config/sxhkd
ln -s ~/dotfiles/scripts ~/scripts
ln -s ~/dotfiles/.colors ~/.colors
ln -s ~/dotfiles/.vimrc ~/.vimrc
ln -s ~/dotfiles/.zshrc ~/.zshrc
ln -s ~/dotfiles/.Xresources ~/.Xresources
ln -s ~/dotfiles/.xinitrc ~/.xinitrc
