#!/bin/sh
mkdir -p ~/.config
ln -s ~/dotfiles/bspwm ~/.config/bspwm
ln -s ~/dotfiles/sxhkd ~/.config/sxhkd
ln -s ~/dotfiles/scripts ~/scripts
ln -s ~/dotfiles/.colors ~/.colors
ln -s ~/dotfiles/.nvimrc ~/.nvimrc
ln -s ~/dotfiles/.zshrc ~/.zshrc
ln -s ~/dotfiles/.gtkrc-2.0 ~/.gtkrc-2.0
ln -s ~/dotfiles/.Xresources ~/.Xresources
ln -s ~/dotfiles/.xinitrc ~/.xinitrc
ln -s ~/dotfiles/compton.conf ~/.config/compton.conf
ln -s ~/dotfiles/.gitconfig ~/.gitconfig
