#! /bin/sh

bspc config split_ratio         0.50
bspc config border_width        1
bspc config window_gap          6
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config normal_border_color none
bspc config active_border_color "#504339"
bspc config urgent_border_color "#504339"
bspc config focused_border_color "#FB6E52"
bspc config presel_border_color none
bspc config top_padding 16

bspc monitor -d main www gvim osu music

bspc rule -a Gimp follow=on floating=on
bspc rule -a Screenkey manage=off

(cd ~/.config/bspwm && ./panel_new) &
(cd ~/.config/bspwm && ./panel) &
stalonetray --geometry 20x1-0+0 --icon-gravity E --grow-gravity E -bg "#262626" -i 14 -d all &
feh --bg-scale ~/wallpapers/131118-1920x1080.jpg
xxkb &
dropboxd &
compton -D1 -cCGfzb
