#! /bin/sh

NORMIFS=$IFS
FIELDIFS=':'
PAD='  '
LPAD='                '

source ~/.config/bspwm/panel_colors

while read -r line; do
  case $line in
    S*)
      sys_infos="${line#?}"
      ;;
    I*)
      mpd_infos="${line#?}"
      ;;
    W*)
      wm_infos=""
      IFS=$FIELDIFS
      set -- ${line#?}
      while [ $# -gt 0 ]; do
        item=$1
        case $item in
          [OoFfUu]*)
            name=${item#?}
            FG=$FOREGROUND
            BG=$BACKGROUND
            case $item in
              O*)
                symbol=
                FG=$BOLD_GREEN
              ;;
              F*)
                symbol=
                FG=$BOLD_GREEN
              ;;
              U*)
                symbol=
                FG=$BOLD_GREEN
              ;;
              o*)
                symbol=
              ;;
              f*)
                symbol=
              ;;
              u*)
                symbol=
              ;;
            esac
            wm_infos="${wm_infos}%{F$FG B$BG A:bspc desktop -f ${name}:}${PAD}${symbol}${PAD}%{A B- F-}"
            ;;
          # L*)
          #   layout=$(printf "[%s]" $(echo "${item#?}" | sed 's/6\(.\).*/\U\1/'))
          #   wm_infos="${wm_infos}%{F$BG B$LAYOUT_BG}%{F$LAYOUT_FG A:bspc desktop -l next:} $layout %{A F$LAYOUT_BG B-}%"
          #   ;;
        esac
        shift
      done
      IFS=$NORMIFS
      ;;
    esac
    printf "%s\n" "%{l}$mpd_infos %{c}$wm_infos %{r}$sys_infos "
done





