#!/bin/sh

bspc config split_ratio         0.50
bspc config border_width        5
bspc config window_gap          10
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config top_padding 0

# Colors
bspc config normal_border_color none
bspc config active_border_color "#525252"
bspc config urgent_border_color "#525252"
bspc config focused_border_color "#1E4E51"
bspc config presel_border_color none

bspc monitor -d 1 2 3 4 5 6 7 8 9

source $(dirname $0)/config
tinyclock &
hsetroot -solid "${WALLCOLOR_A}" &
twitch_daemon &
