#! /bin/sh

bspc config split_ratio         0.50
bspc config border_width        2
bspc config window_gap          5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config top_padding 20

# Colors
bspc config normal_border_color none
bspc config active_border_color "#525252"
bspc config urgent_border_color "#525252"
bspc config focused_border_color "#746C48"
bspc config presel_border_color none

bspc monitor -d     
# bspc monitor -d 1 2 3 4 5

source ~/.config/bspwm/panel_colors
# Plan to change this two panels to one
# (cd ~/.config/bspwm && ./panel_new) &
# (cd ~/.config/bspwm && ./panel) &
(cd ~/.config/bspwm && ./panel) &
nitrogen --restore &
dropboxd &
compton &
