#!/bin/sh

source $(dirname $0)/panel_colors

EDGEWIDTH=50
DMENUWIDTH=$(($SCREENWIDTH - $(($EDGEWIDTH + $EDGEWIDTH))))

XPOS=$EDGEWIDTH
YPOS=$(($(($SCREENHEIGHT / 2)) - 15))

FGSELECT="#746C48"
BGSELECT="#746C48"
FG="#BEA492"
BG="#181512"
FONT="xft:tewi:size=9"

dmenu_run -w $DMENUWIDTH -x $XPOS -y $YPOS -fn ${FONT} -nb $BG -nf $FG -sb $BGSELECT -dim 0.6
