#!/bin/sh

source $(dirname $0)/config

DMENUWIDTH=1900
DMENUHEIGHT=5
XPOS=10
YPOS=0

BGSELECT="#82444C"
FG="#A5A5A5"
BG="#1B1D20"

dmenu_run -w $DMENUWIDTH -h $DMENUHEIGHT -x $XPOS -y $YPOS -fn ${FONT2} -nb $BG -nf $FG -sb $BGSELECT
