#! /bin/sh

source ~/.config/bspwm/panel_colors

if [ $(pgrep -cx panel) -gt 1 ] ; then
  printf "%s\n" "The panel is already running." >&2
  exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc control --subscribe > "$PANEL_FIFO" &

# Dzen2
# ~/.config/bspwm/statusbar > "$PANEL_FIFO" &
# cat "$PANEL_FIFO" | ~/.config/bspwm/panel_bar | dzen2 -x ${EDGEWIDTH} -y ${EDGEWIDTH} -h $PANEL_HEIGHT -dock -ta l -title-name panel -fn "${PANEL_FONT_FAMILY}:pixelsize=${PANEL_FONT_SIZE}" -fg "$FOREGROUND" -bg "$BACKGROUND" -w "${BARWIDTH}" &

# Bar-aint-recursive
export LANG=en_US.UTF-8
~/.config/bspwm/statusbar_bar > "$PANEL_FIFO" &
conky -c ~/scripts/bspwm_bar_conkyrc > "$PANEL_FIFO" &
cat "$PANEL_FIFO" | ~/.config/bspwm/bspwm_panel_bar | bar -p -g "$GEOMETRY" -f "$FONT1,$FONT2" -B "$BACKGROUND" -F "$FOREGROUND" | sh &
wait
