#! /bin/sh

source ~/.config/bspwm/panel_colors

if [ $(pgrep -cx panel) -gt 1 ] ; then
  printf "%s\n" "The panel is already running." >&2
  exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc control --subscribe > "$PANEL_FIFO" &
~/.config/bspwm/statusbar > "$PANEL_FIFO" &

cat "$PANEL_FIFO" | ~/.config/bspwm/panel_bar | dzen2 -x ${EDGEWIDTH} -y ${EDGEWIDTH} -h $PANEL_HEIGHT -dock -ta l -title-name panel -fn "${PANEL_FONT_FAMILY}" -fg "$FOREGROUND" -bg "$BACKGROUND" -w "${BARWIDTH}" &

wait
