#! /bin/sh

if [ $(pgrep -cx panel) -gt 1 ] ; then
  printf "%s\n" "The panel is already running." >&2
  exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc control --subscribe > "$PANEL_FIFO" &

. ./panel_colors
FONT_FAMILY='xft:monaco:size=8'
cat "$PANEL_FIFO" | ./panel_dzen2 -f "$FONT_FAMILY" | dzen2 -h 16 -w 260 -dock -ta l -title-name panel -fn "${FONT_FAMILY}" -fg "$COLOR_FOREGROUND" -bg "$COLOR_BACKGROUND"
