#! /bin/sh

source ~/.config/bspwm/panel_colors

get_mus() {
  CURRENT=`mpc current`
  STATUS=`mpc status | grep "\[" | awk '{print $1}' | sed 's/\[//;s/\]//'`

  if [ "$CURRENT" = "" ]; then
      echo -e "\ue057 mpd stopped"
  else
      if [ "$STATUS" = "playing" ]; then
        echo -e "%{F$BOLD_RED}\ue058%{F-} `mpc current | awk '{split($0,a," - "); printf "%s %s %s", a[1], "'%{F$BOLD_RED}'>'%{F-}'", a[2];}'`"
      else
        echo -e "%{F$BOLD_RED}\ue059%{F-} `mpc current | awk '{split($0,a," - "); printf "%s %s %s", a[1], "'%{F$BOLD_RED}'>'%{F-}'", a[2];}'`"
      fi
  fi
}

get_layout() {
  CURRENT=`xkb-switch`
  echo -e "%{F$BOLD_RED}\ue0b1%{F-} $CURRENT"
}

get_vol() {
  AMASTER=`amixer get Master | grep Left | egrep -o "[0-9]+%" | sed s/\%//`
  ASTATUS=`amixer get Master | grep Left | egrep -o "\[[a-z]+\]" | sed 's/\[//;s/\]//'`
  if [ "$ASTATUS" = "off" ]; then
    echo -e "%{F$BOLD_RED }\ue04f%{F-} $AMASTER"
  else
    if [[ "$AMASTER" -gt 75 ]]; then
      echo -e "%{F$BOLD_RED }\ue05d%{F-} $AMASTER"
    else
      echo -e "%{F$BOLD_RED }\ue050%{F-} $AMASTER"
    fi
  fi
}

while true ; do
  echo "I $(get_mus) $(get_vol) $(get_layout)"
  sleep 1
done
