#!/bin/sh

bspwm_workspaces() {
    min=1
    max=10

    workspace_icons="α β γ δ ε ζ η θ ι λ"
    set -- $workspace_icons
    box="["
    for i in `seq $min $max`
    do
        if [ $(bspc query -D -d .occupied --names | grep "^$i$") ]; then
            box="$box { name: $i, focused:"
            if [ $(bspc query -D -d .focused --names | grep "^$i$") ]; then
		box="$box true"
            else
		box="$box false"
            fi
            box="$box, urgent:"
            if [ $(bspc query -D -d .urgent --names | grep "^$i$") ]; then
		box="$box true"
            else
		box="$box false"
            fi
	    box="$box },"
        fi
        shift
    done

    box="${box%,} ]" # Remove the last comma
    echo $box
}

if [ "$1" = "bspwm" ]; then
    bspwm_workspaces

    bspc subscribe desktop node_transfer | while read -r _ ; do
	bspwm_workspaces
    done

fi

if [ "$1" = "sway" ]; then
    echo $(swaymsg -t get_workspaces -r)
    swaymsg -t subscribe -m '["workspace"]' | while read -r _ ; do
	echo $(swaymsg -t get_workspaces -r)
    done
fi
