#!/bin/bash

print_usage() {
  echo "Usage: change_theme.sh name_of_theme config_file\n"
  echo "-l: list of themes"
  exit 1
}

get_all_themes() {
  echo ls ~/.colors/
  exit 0
}

if [ $1 = "-l" ]; then
  $(get_all_themes)
fi

if [ $# != 2 ]; then
  echo -e $(print_usage)
fi

if [ ! -e ~/.colors/$1 ]; then
  echo "Can't read file!"
  echo -e $(print_usage)
fi

for line in $(get_theme.sh ~/.colors/$1); do
  COL_TYPE=$(echo $line | awk '{split($0,a,"="); print a[1]}')
  COL_VALUE=$(echo $line | awk '{split($0,a,"="); print a[2]}')
  sed -i "s/$COL_TYPE=\"#[A-Za-z0-9]*\"/$COL_TYPE=$COL_VALUE/" $2
done
# ~/get_theme.sh ~/.colors/$1
