#!/bin/sh

source $(dirname $0)/config

DMENUWIDTH=1910
DMENUHEIGHT=30
XPOS=5
YPOS=0

BGSELECT="#77DFD8"
FG="#FFFFFF"
BG="#242424"

dmenu_run -w $DMENUWIDTH -h $DMENUHEIGHT -x $XPOS -y $YPOS -fn ${FONT2} -nb $BG -nf $FG -sb $BGSELECT
