#!/bin/sh

source $(dirname $0)/config

DMENUWIDTH=1920
DMENUHEIGHT=30
XPOS=0
YPOS=0

BGSELECT="#5D5D5D"
FG="#DEDEDE"
BG="#242424"

dmenu_run -w $DMENUWIDTH -h $DMENUHEIGHT -x $XPOS -y $YPOS -fn ${FONT2} -nb $BG -nf $FG -sb $BGSELECT
