#!/bin/sh

source $(dirname $0)/config

DMENUWIDTH=1900
DMENUHEIGHT=30
XPOS=10
YPOS=10

BGSELECT="#888888"
FG="#FFFFFF"
BG="#1D1D1D"

dmenu_run -w $DMENUWIDTH -h $DMENUHEIGHT -x $XPOS -y $YPOS -fn ${FONT2} -nb $BG -nf $FG -sb $BGSELECT
