#!/bin/bash

FONT="-misc-termsyn.icons-medium-r-normal--11-79-100-100-c-60-iso8859-1"
PAD='   '
ACT='onstart=uncollapse;button1=exit;button3=exit'
YPOS='20'
TIME='4'

FG="#CCCCDC"
BG="#141414"

bar_bg="#444444"
bar_fg="#27B2DB"
label="#BD25B4"
highlight="#BD25B4"
highlight2="#1C1C1C"
warn="#C23127"

OPTIONS="-bg ${BG} -fg ${FG} -y ${YPOS} -e ${ACT} -ta 'c'"
