#!/bin/sh

source $(dirname $0)/config

(echo " $@"; sleep $DURATION)\
| lemonbar \
      -f "$FONT1","$FONT2"\
      -F "$FOREGROUND"\
      -B "$BACKGROUND"\
      -g "$NOTIFY_GEOMETRY"\
      -u $LINEHEIGHT
