#!/bin/sh
for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    if [ "$m" = "HDMI-A-0" ]; then
        MONITOR=$m TRAYPOS="right" polybar example &
    else
        MONITOR=$m polybar example &
    fi
done
