#!/bin/sh
#
# Created by Queyenth
#

usage() {
  echo "usage: twitch channel quality"
}

if [[ $1 == '' ]] ; then
  usage
  exit 1
fi

# We should get available quality
if [[ $2 == '' ]] ; then
  LIVESTREAMER=`livestreamer twitch.tv/$1 -Q`
  notify-send "$1" "$LIVESTREAMER"
  exit 0
fi

# Channel - $1
# Quality - $2
livestreamer -p vlc "twitch.tv/$1" $2
