#!/bin/bash
#
# Inspired by
#   z3bra - http://blog.z3bra.org/2014/04/pop-it-up.html
#   bruenig - https://bbs.archlinux.org/viewtopic.php?id=46608
#   Windelicato - http://github.com/windelicato

err() {
  echo "$1"
  exit 1
}

usage() {
  echo "usage: volumenotify [option] [argument]"
  echo
  echo "Options:"
  echo "   +, -i, --increase  - increase volyme by \`argument'"
  echo "   -, -d, --decrease  - decrease volyme by \`argument'"
  echo "   !, -t, --toggle    - mute/unmute"
  echo "   -h, --help         - display this"
  exit
}

case $1 in
    '+'|'-i'|'--increase'|'up')
        [ -z "$2" ] && err "No argument specified for increase"
        PONYMIXARG="increase ${2}"
        ;;
    '-'|'-d'|'--decrease'|'down')
        [ -z "$2" ] && err "No argument specified for decrease"
        PONYMIXARG="decrease ${2}"
        ;;
    '!'|'-t'|'--toggle')
        PONYMIXARG="toggle"
        ;;
    '='|'-s'|'--set')
        PONYMIXARG="set-volume ${2}"
        ;;
    ''|'-h'|'--help')
        usage
        ;;
    *)
        err "Unrecognized option \`$1', see volumenotify --help"
esac

ponymix $PONYMIXARG

volume=$(ponymix get-volume)

case $1 in
  '+'|'-i'|'--increase'|'-'|'-d'|'--decrease'|'up'|'down'|'='|'-s'|'--set')
    notify-send -e -h int:value:"$volume" -h string:x-canonical-private-synchronous:volume_notif -u low -i audio-volume-high "Volume: $volume"
    ;;
  '!'|'-t'|'--toggle')
    if ponymix is-muted ; then
      notify-send -e -h string:x-canonical-private-synchronous:volume_notif -u low -i audio-volume-muted "Volume: muted"
    else
      notify-send -e -h int:value:"$volume" -h string:x-canonical-private-synchronous:volume_notif -u low -i audio-volume-high "Volume: $volume"
    fi
    ;;
esac

canberra-gtk-play -i audio-volume-change -d "changeVolume"
if pidof -q eww ; then
    ~/src/eww/target/release/eww update volume=$volume
    ~/src/eww/target/release/eww update volume_is_muted=$(ponymix is-muted || echo true)
fi
