#!/bin/bash
#
# Inspired by
#   z3bra - http://blog.z3bra.org/2014/04/pop-it-up.html
#   bruenig - https://bbs.archlinux.org/viewtopic.php?id=46608
#   Windelicato - http://github.com/windelicato

BAR_LENGTH=20
BAR_CHAR='='

err() {
  echo "$1"
  exit 1
}

usage() {
  echo "usage: volumenotify [option] [argument]"
  echo
  echo "Options:"
  echo "   +, -i, --increase  - increase volyme by \`argument'"
  echo "   -, -d, --decrease  - decrease volyme by \`argument'"
  echo "   !, -t, --toggle    - mute/unmute"
  echo "   -h, --help         - display this"
  exit
}
msgId="991049"

case $1 in
  '+'|'-i'|'--increase')
    [ -z "$2" ] && err "No argument specified for increase"
    PONYMIXARG="increase ${2}"
    ;;
  '-'|'-d'|'--decrease')
    [ -z "$2" ] && err "No argument specified for decrease"
    PONYMIXARG="decrease ${2}"
    ;;
  '!'|'-t'|'--toggle')
    PONYMIXARG="toggle"
    ;;
  ''|'-h'|'--help')
    usage
    ;;
  *)
    err "Unrecognized option \`$1', see volumenotify --help"
esac

ponymix $PONYMIXARG

# volumelevel=$(ponymix get-volume)
# if ponymix is-muted; then
#     echo 0 > /tmp/wob.fifo
# else
#     echo $volumelevel > /tmp/wob.fifo
# fi

bar=$(volumebar)

case $1 in
  '+'|'-i'|'--increase'|'-'|'-d'|'--decrease')
    dunstify -a "changeVolume" -u low -i audio-volume-high -r "$msgId" "${bar}"
    ;;
  '!'|'-t'|'--toggle')
    dunstify -a "changeVolume" -u low -i audio-volume-muted -r "$msgId" "muted/unmuted"
    ;;
esac

canberra-gtk-play -i audio-volume-change -d "changeVolume"
